// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearRequestLog(arg1) {
  return window['go']['main']['App']['ClearRequestLog'](arg1);
}

export function CreateCollection(arg1, arg2) {
  return window['go']['main']['App']['CreateCollection'](arg1, arg2);
}

export function CreateEndpoint(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateEndpoint'](arg1, arg2, arg3);
}

export function CreateFolder(arg1, arg2) {
  return window['go']['main']['App']['CreateFolder'](arg1, arg2);
}

export function CreateServer(arg1) {
  return window['go']['main']['App']['CreateServer'](arg1);
}

export function DeleteCollection(arg1) {
  return window['go']['main']['App']['DeleteCollection'](arg1);
}

export function DeleteEndpoint(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteEndpoint'](arg1, arg2, arg3);
}

export function DeleteFolder(arg1, arg2) {
  return window['go']['main']['App']['DeleteFolder'](arg1, arg2);
}

export function DeleteServer(arg1) {
  return window['go']['main']['App']['DeleteServer'](arg1);
}

export function DiscardBreakpoint(arg1) {
  return window['go']['main']['App']['DiscardBreakpoint'](arg1);
}

export function ExportCollection(arg1) {
  return window['go']['main']['App']['ExportCollection'](arg1);
}

export function GetCollections() {
  return window['go']['main']['App']['GetCollections']();
}

export function GetPendingBreakpoints() {
  return window['go']['main']['App']['GetPendingBreakpoints']();
}

export function GetRequestLog(arg1) {
  return window['go']['main']['App']['GetRequestLog'](arg1);
}

export function GetServers() {
  return window['go']['main']['App']['GetServers']();
}

export function ImportCollection(arg1) {
  return window['go']['main']['App']['ImportCollection'](arg1);
}

export function ImportFromOpenAPI(arg1) {
  return window['go']['main']['App']['ImportFromOpenAPI'](arg1);
}

export function IsServerRunning(arg1) {
  return window['go']['main']['App']['IsServerRunning'](arg1);
}

export function ReleaseBreakpoint(arg1, arg2) {
  return window['go']['main']['App']['ReleaseBreakpoint'](arg1, arg2);
}

export function RenameFolder(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameFolder'](arg1, arg2, arg3);
}

export function RestartServer(arg1) {
  return window['go']['main']['App']['RestartServer'](arg1);
}

export function StartServer(arg1) {
  return window['go']['main']['App']['StartServer'](arg1);
}

export function StopServer(arg1) {
  return window['go']['main']['App']['StopServer'](arg1);
}

export function UpdateCollection(arg1, arg2) {
  return window['go']['main']['App']['UpdateCollection'](arg1, arg2);
}

export function UpdateEndpoint(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateEndpoint'](arg1, arg2, arg3, arg4);
}

export function UpdateServer(arg1) {
  return window['go']['main']['App']['UpdateServer'](arg1);
}
