// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function ClearRequestLog(arg1:string):Promise<void>;

export function CreateCollection(arg1:string,arg2:string):Promise<backend.Collection>;

export function CreateEndpoint(arg1:string,arg2:string,arg3:backend.Endpoint):Promise<backend.Collection>;

export function CreateFolder(arg1:string,arg2:string):Promise<backend.Collection>;

export function CreateServer(arg1:backend.ServerConfig):Promise<backend.ServerInfo>;

export function DeleteCollection(arg1:string):Promise<void>;

export function DeleteEndpoint(arg1:string,arg2:string,arg3:string):Promise<backend.Collection>;

export function DeleteFolder(arg1:string,arg2:string):Promise<backend.Collection>;

export function DeleteServer(arg1:string):Promise<void>;

export function DiscardBreakpoint(arg1:string):Promise<boolean>;

export function ExportCollection(arg1:string):Promise<string>;

export function GetCollections():Promise<Array<backend.Collection>>;

export function GetPendingBreakpoints():Promise<Array<backend.BreakpointHit>>;

export function GetRequestLog(arg1:string):Promise<Array<backend.RequestLogEntry>>;

export function GetServers():Promise<Array<backend.ServerInfo>>;

export function ImportCollection(arg1:string):Promise<backend.Collection>;

export function ImportFromOpenAPI(arg1:string):Promise<backend.Collection>;

export function IsServerRunning(arg1:string):Promise<boolean>;

export function ReleaseBreakpoint(arg1:string,arg2:backend.MockResponse):Promise<boolean>;

export function RenameFolder(arg1:string,arg2:string,arg3:string):Promise<backend.Collection>;

export function RestartServer(arg1:string):Promise<void>;

export function StartServer(arg1:string):Promise<void>;

export function StopServer(arg1:string):Promise<void>;

export function UpdateCollection(arg1:string,arg2:backend.CollectionUpdate):Promise<backend.Collection>;

export function UpdateEndpoint(arg1:string,arg2:string,arg3:string,arg4:backend.Endpoint):Promise<backend.Collection>;

export function UpdateServer(arg1:backend.ServerConfig):Promise<backend.ServerInfo>;
