import type {
  Collection,
  ServerInfo,
  ServerConfig,
  RequestLogEntry,
  BreakpointHit,
  Endpoint,
  MockResponse,
} from './types'

// Re-export Go binding wrappers with proper types.
// The wailsjs directory is auto-generated by `wails dev` / `wails generate`.
import * as App from '../../wailsjs/go/main/App'
import { EventsOn } from '../../wailsjs/runtime/runtime'

// ── Collections ──────────────────────────────────────────────────────────────

export const getCollections = (): Promise<Collection[]> => App.GetCollections()

export const createCollection = (name: string, description: string): Promise<Collection> =>
  App.CreateCollection(name, description)

export const updateCollection = (
  id: string,
  upd: { name: string; description: string; variables: Record<string, string> },
): Promise<Collection> => App.UpdateCollection(id, upd)

export const deleteCollection = (id: string): Promise<void> => App.DeleteCollection(id)

export const exportCollection = (id: string): Promise<string> => App.ExportCollection(id)

export const importCollection = (data: string): Promise<Collection> => App.ImportCollection(data)

export const importFromOpenAPI = (data: string): Promise<Collection> => App.ImportFromOpenAPI(data)

// ── Folders ──────────────────────────────────────────────────────────────────

export const createFolder = (collectionID: string, name: string): Promise<Collection> =>
  App.CreateFolder(collectionID, name)

export const renameFolder = (
  collectionID: string,
  folderID: string,
  name: string,
): Promise<Collection> => App.RenameFolder(collectionID, folderID, name)

export const deleteFolder = (collectionID: string, folderID: string): Promise<Collection> =>
  App.DeleteFolder(collectionID, folderID)

// ── Endpoints ────────────────────────────────────────────────────────────────

export const createEndpoint = (
  collectionID: string,
  folderID: string,
  ep: Endpoint,
): Promise<Collection> => App.CreateEndpoint(collectionID, folderID, ep)

export const updateEndpoint = (
  collectionID: string,
  folderID: string,
  endpointID: string,
  ep: Endpoint,
): Promise<Collection> => App.UpdateEndpoint(collectionID, folderID, endpointID, ep)

export const deleteEndpoint = (
  collectionID: string,
  folderID: string,
  endpointID: string,
): Promise<Collection> => App.DeleteEndpoint(collectionID, folderID, endpointID)

// ── Servers ──────────────────────────────────────────────────────────────────

export const getServers = (): Promise<ServerInfo[]> => App.GetServers()

export const createServer = (cfg: ServerConfig): Promise<ServerInfo> => App.CreateServer(cfg)

export const updateServer = (cfg: ServerConfig): Promise<ServerInfo> => App.UpdateServer(cfg)

export const startServer = (id: string): Promise<void> => App.StartServer(id)

export const stopServer = (id: string): Promise<void> => App.StopServer(id)

export const deleteServer = (id: string): Promise<void> => App.DeleteServer(id)

export const getRequestLog = (serverID: string): Promise<RequestLogEntry[]> =>
  App.GetRequestLog(serverID)

export const clearRequestLog = (serverID: string): Promise<void> => App.ClearRequestLog(serverID)

// ── Breakpoints ───────────────────────────────────────────────────────────────

export const getPendingBreakpoints = (): Promise<BreakpointHit[]> => App.GetPendingBreakpoints()

export const releaseBreakpoint = (id: string, resp: MockResponse): Promise<boolean> =>
  App.ReleaseBreakpoint(id, resp)

export const discardBreakpoint = (id: string): Promise<boolean> => App.DiscardBreakpoint(id)

// ── Events ────────────────────────────────────────────────────────────────────

export const onServerStatus = (cb: (servers: ServerInfo[]) => void) => EventsOn('server:status', cb)

export const onRequestLogged = (cb: (entry: RequestLogEntry) => void) =>
  EventsOn('request:logged', cb)

export const onBreakpointHit = (cb: (hit: BreakpointHit) => void) => EventsOn('breakpoint:hit', cb)

export const onBreakpointReleased = (cb: (id: string) => void) =>
  EventsOn('breakpoint:released', cb)
